### ISSUE TITLE
[proposal] user-friendly web server presenting the data found in the redis db

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/rexplorer#32]
`rexplorer` fetches a lot of useful info, but consuming it directly from `redis` (not even talking about the requirement of actually needing to know how to install `rexplorer` and using the binary from command line (correctly)) is not something the average user will be able to pull of (or at least not willing to pull of).

Therefore it could be useful (and relatively simple to do), to provide a web server that we can host (but others can host as well, given it is all OSS), which acts as a client of the redis-db (and thus is probably running on the same server as the `rexplorer` instance populating that redis-db), and provides it in a very useful way.

* It would provide a list of all unique addresses (could even be sorted by balance, as to give at least some sensible order);
* It would allow you to look up a wallet address (or click through one of the already displayed addresses), and see its balance and locked/unlocked outputs);
* It would provide some global stats as graphs on the home page, and on the wallet page it could provide per-wallet graphs for the coin state stat, as well as how much it owns in total for all its wallets: individual, and all referred multisig wallets);

**Comment by GlenDC** [comment]
Overal I would like to keep the design as minimalistic as possible, with the goal of keeping it simple enough to develop and maintain with the limited resources we have, as well as keep the content focussed and clear for the end user.

![img_1241](https://user-images.githubusercontent.com/3900482/45611558-1c58ab80-ba60-11e8-9251-bd5343df46a2.JPG)
> possible design: home page
![img_1240](https://user-images.githubusercontent.com/3900482/45611661-70639000-ba60-11e8-8f70-d23a7ad4210e.JPG)
> possible design: wallet page

**Comment by GlenDC** [comment]
Web server would be in Golang as the performance is great by default, and it's the language I am most comfortable with to develop such a project (fast and correct). Keeping it simple without any need for GUI frameworks will make it do-able as well without much hassle, and for graphs there are Go as well as JS libraries we can use.

**Comment by despiegk** [comment]
this was already planned to be done on our 3bot
